### ISSUE TITLE
Flask + Arachne + Scrapy DigitalOcean Deployment problem

### ISSUE THREAD

**Issue by samsoft00** [kirankoduru/Arachne#6]
Great job Kiran, for couple of days now, i've been battling with the deployment of Flask with Arachne on DigitalOcean, first here is my project structure on the server

|--------FlaskApp
|----------------FlaskApp
|-----------------------static
|-----------------------templates
|-----------------------venv
|-----------------------app.py
|-----------------------etc
|----------------flaskapp.wsgi

Navigating to my IP: http://104.131.31.XXX, it display internal here, but if i run "sudo python app.py" and navigate to http://104.131.31.XXX:8888, it display my site. i check log/apache2/error.log for the error, i found this. 

```
'/var/www/FlaskApp/flaskapp.wsgi' cannot be loaded as Python module.
[Fri Dec 04 03:07:12.844591 2015] [:error] [pid 622] [client 169.255.236.76:17980] mod_wsgi (pid=622): Exception occurred processing WSGI script '/var/www/FlaskApp/flaskapp.wsgi'.
[Fri Dec 04 03:07:12.844640 2015] [:error] [pid 622] [client 169.255.236.76:17980] Traceback (most recent call last):
[Fri Dec 04 03:07:12.844688 2015] [:error] [pid 622] [client 169.255.236.76:17980]   File "/var/www/FlaskApp/flaskapp.wsgi", line 8, in <module>
[Fri Dec 04 03:07:12.844822 2015] [:error] [pid 622] [client 169.255.236.76:17980]     from app import app
[Fri Dec 04 03:07:12.844868 2015] [:error] [pid 622] [client 169.255.236.76:17980] ImportError: No module named app
```
here is my WSGI configuration 
```
import sys
import logging
logging.basicConfig(stream=sys.stderr)
sys.path.insert(0,"/var/www/FlaskApp/")

from app import app as application 
application.secret_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```
Flask Config  /etc/apache2/sites-available/FlaskApp.conf

```
<VirtualHost *:80>
                ServerName 104.131.31.XXX
                ServerAdmin admin@104.131.31.XXX
                WSGIScriptAlias / /var/www/FlaskApp/flaskapp.wsgi
                <Directory /var/www/FlaskApp/FlaskApp/>
                        Order allow,deny
                        Allow from all
                </Directory>
                Alias /static /var/www/FlaskApp/FlaskApp/static
                <Directory /var/www/FlaskApp/FlaskApp/static/>
                        Order allow,deny
                        Allow from all
                </Directory>
                ErrorLog ${APACHE_LOG_DIR}/error.log
                LogLevel warn
                CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

Here is my app.py

```
app = Arachne(__name__)

resource = WSGIResource(reactor, reactor.getThreadPool(), app)
site = Site(resource)
reactor.listenTCP(8888, site)

if __name__ == '__main__':
	reactor.run()
```

Please, what's missing????

**Comment by samsoft00** [comment]
After alot of work around, No error regarding import  after edit WSGI configuration
```
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '.')))
```

but issue now is can't find SPIDER SETTINGS
```
[Fri Dec 04 09:30:25.384981 2015] [:error] [pid 5107] [client 169.255.236.76:31608] mod_wsgi (pid=5107): Target WSGI script '/var/www/FlaskApp/flaskapp.wsgi' cannot be loaded as Python module.
[Fri Dec 04 09:30:25.385052 2015] [:error] [pid 5107] [client 169.255.236.76:31608] mod_wsgi (pid=5107): Exception occurred processing WSGI script '/var/www/FlaskApp/flaskapp.wsgi'.
[Fri Dec 04 09:30:25.385085 2015] [:error] [pid 5107] [client 169.255.236.76:31608] Traceback (most recent call last):
[Fri Dec 04 09:30:25.385108 2015] [:error] [pid 5107] [client 169.255.236.76:31608]   File "/var/www/FlaskApp/flaskapp.wsgi", line 10, in <module>
[Fri Dec 04 09:30:25.385140 2015] [:error] [pid 5107] [client 169.255.236.76:31608]     from FlaskApp import app as application
[Fri Dec 04 09:30:25.385152 2015] [:error] [pid 5107] [client 169.255.236.76:31608]   File "/var/www/FlaskApp/FlaskApp/app.py", line 16, in <module>
[Fri Dec 04 09:30:25.385168 2015] [:error] [pid 5107] [client 169.255.236.76:31608]     app = Arachne(__name__)
[Fri Dec 04 09:30:25.385178 2015] [:error] [pid 5107] [client 169.255.236.76:31608]   File "/usr/local/lib/python2.7/dist-packages/arachne/flaskapp.py", line 21, in __init__
[Fri Dec 04 09:30:25.385195 2015] [:error] [pid 5107] [client 169.255.236.76:31608]     self.validate_spider_settings()
[Fri Dec 04 09:30:25.385205 2015] [:error] [pid 5107] [client 169.255.236.76:31608]   File "/usr/local/lib/python2.7/dist-packages/arachne/flaskapp.py", line 78, in validate_spider_settings
[Fri Dec 04 09:30:25.385220 2015] [:error] [pid 5107] [client 169.255.236.76:31608]     raise SettingsException('SPIDER_SETTINGS missing')
[Fri Dec 04 09:30:25.385241 2015] [:error] [pid 5107] [client 169.255.236.76:31608] SettingsException: SPIDER_SETTINGS missing
```

**Comment by kirankoduru** [comment]
I am not sure about deploying with wsgi since I haven't used it a lot but does moving your wsgi file help to in the inner `FlaskApp` directory?

```
|--------FlaskApp
|----------------FlaskApp
|-----------------------static
|-----------------------templates
|-----------------------venv
|-----------------------app.py
|-----------------------etc
|-----------------------flaskapp.wsgi
```

**Comment by samsoft00** [comment]
@kirankoduru I've moved flaskapp.wsgi to inner FlaskApp but the problem still persist, if i run sudo python app.py and navigate to 104.131.31.XXX:8888, What do you think i should do now?
```
[client 169.255.236.76:5683] SettingsException: SPIDER_SETTINGS missing
```

**Comment by kirankoduru** [comment]
@samsoft00  can you paste your directory structure here again?

**Comment by samsoft00** [comment]
@kirankoduru Thanks so much, i've snap my command prompt screen and send it to your email address, kindly check your email. Thanks

**Comment by samsoft00** [comment]
Just checking now, since i've move my flaskapp.wsgi to inner FlaskApp, i change the configuration here 
```
import sys
import logging
logging.basicConfig(stream=sys.stderr)
sys.path.insert(0,"/var/www/FlaskApp/FlaskApp/") <-----

from app import app as application 
application.secret_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```
The Error now says 
```
[Fri Dec 04 11:10:55.743996 2015] [:error] [pid 7300] [client 169.255.236.76:2240] mod_wsgi (pid=7300): Target WSGI script '/var/www/FlaskApp/FlaskApp/flaskapp.wsgi' cannot be loaded as Python module.
[Fri Dec 04 11:10:55.744068 2015] [:error] [pid 7300] [client 169.255.236.76:2240] mod_wsgi (pid=7300): Exception occurred processing WSGI script '/var/www/FlaskApp/FlaskApp/flaskapp.wsgi'.
[Fri Dec 04 11:10:55.744091 2015] [:error] [pid 7300] [client 169.255.236.76:2240] Traceback (most recent call last):
[Fri Dec 04 11:10:55.744115 2015] [:error] [pid 7300] [client 169.255.236.76:2240]   File "/var/www/FlaskApp/FlaskApp/flaskapp.wsgi", line 10, in <module>
[Fri Dec 04 11:10:55.744193 2015] [:error] [pid 7300] [client 169.255.236.76:2240]     from FlaskApp import app as application
[Fri Dec 04 11:10:55.744216 2015] [:error] [pid 7300] [client 169.255.236.76:2240] ImportError: No module named FlaskApp

```
In apache2/log/error.log

**Comment by samsoft00** [comment]
Thanks @kirankoduru, everything work when i remove this
```
resource = WSGIResource(reactor, reactor.getThreadPool(), app)
site = Site(resource)
reactor.listenTCP(8888, site)
```

use app.run() instead of reactor.run()

**Comment by samsoft00** [comment]
Just discovered a problem... 

After removing this reactor.listenTCP(8888, site), it work perfectly, i was able to navigate /spiders and /run-spiders/<spider_name> but there's a problem, it'll show "status": "<spider_name> running" but nothing scrap? checking out apache log, it display 
```
[Sat Dec 05 01:47:24.238449 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [-] Log opened.
[Sat Dec 05 01:47:24.293634 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [scrapy] Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
[Sat Dec 05 01:47:24.338804 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [scrapy] Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
[Sat Dec 05 01:47:24.340387 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [scrapy] Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
[Sat Dec 05 01:47:24.343616 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [scrapy] Enabled item pipelines: CareerPipeline
[Sat Dec 05 01:47:24.343827 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [scrapy] Spider opened
[Sat Dec 05 01:47:24.344875 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [scrapy] Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
[Sat Dec 05 01:47:24.346659 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [-] TelnetConsole starting on 44500
[Sat Dec 05 01:47:24.346802 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [scrapy] Telnet console listening on 127.0.0.1:44500
[Sat Dec 05 01:47:24.347510 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [-] WebService starting on 6080
[Sat Dec 05 01:47:24.347673 2015] [:error] [pid 16687] 2015-12-05 01:47:24-0500 [scrapy] Web service listening on 127.0.0.1:6080
```

**Comment by kirankoduru** [comment]
Did you log something in the spider?

**Comment by samsoft00** [comment]
No, i don't log anything

**Comment by samsoft00** [comment]
I don't know what else to do... if there's no solution, i think removing Arachne will be option!

**Comment by kirankoduru** [comment]
I am not sure how else can I help you until I see the complete code.

**Comment by samsoft00** [comment]
Here is the whole source code

https://github.com/samsoft00/careervacancy

**Comment by samsoft00** [comment]
Looking at the code and try it on a server will give you idea of what happening, 
https://github.com/samsoft00/careervacancy
if you're not ready to support your library , kindly let me know.

thanks

**Comment by kirankoduru** [comment]
Please create a pull request for fixing the things you might want to change in the library. Until then I will close this issue.

**Comment by kirankoduru** [comment]
Hey @samsoft00 ! I created a [Dockerfile](https://github.com/kirankoduru/arachne-demo/blob/master/Dockerfile) in the demo project. Maybe that might be something that would ease your process of deploying projects.
